language: python
sudo: false

python:
   - "2.7"
   - "3.5"
   - "3.6"

branches:
    only:
        - master
        - develop

install:
    - pip install --upgrade pip setuptools wheel
    - pip install --upgrade pytest
    - pip install six
    - pip install codecov
    - pip install pytest-cov
    - pip install pytest-pep8
    - pip install --only-binary=numpy numpy # Otherwise this would take ages
    - pip install https://github.com/alchemistry/alchemtest/archive/master.zip
    - pip install -e .

script:
    - py.test --cov alchemlyb src/alchemlyb/tests

after_success:
    - codecov
