language: python
sudo: required
dist: xenial

env:
  global:
    - MPLBACKEND=agg

python:
   - "3.7"
   - "3.8"
   - "3.9"

branches:
    only:
        - master
        - develop

install:
    - pip install --upgrade pip setuptools wheel
    - pip install --upgrade pytest
    - pip install codecov pytest-cov pytest-pep8
    - pip install --only-binary=numpy numpy # Otherwise this would take ages
    - pip install https://github.com/alchemistry/alchemtest/archive/master.zip
    - pip install -e .

script:
    - pytest --cov alchemlyb src/alchemlyb/tests

after_success:
    - codecov
